### ISSUE TITLE
Algebra skript lässt sich unter miktex nicht kompilieren

### ISSUE THREAD

**Issue by CBenni** [stev47/uni#2]
Es wirft mehrere hundert fehler, sowohl unter windows als auch mit make auf linux. Wäre es möglich ein fertiges PDF hochzuladen? Mehrere distros simultan zu installieren scheint mir keine gute idee zu sein.
Danke!

**Comment by stev47** [comment]
viele skripte werden automatisch kompiliert und stehen unter http://hilbsn.mooo.com/ts zur verfügung (gehostet auf den servern der uni, deshalb leider desöfteren down).
kompilierte pdfs kommen aus verschiedenen gründen nicht ins git-repo, hauptsächlich weil sie die größe des ganzen repos aufblähen.

zum kompilieren ist mindestens texlive 2012 erforderlich (oder äquivalente latex pakete), auf den stud-pool-rechnern funktioniert es also einwandfrei. Wenn du unter windows kompilierst müsstest du nur drauf achten, dass der ordner `common` im `TEXINCLUDE` pfad ist (die makefile unter linux macht das selbst)

**Comment by CBenni** [comment]
Mh. Ich hab heute versucht es im stud pool zu kompilieren, dabei aber genau dieselben Fehler wie unter Windows bekommen, und dabei hab ich einfach make ausgeführt... Ich werde mal versuchen, das skript vom uni server zu ziehen, falls der mal online kommt. Danke.

**Comment by stev47** [comment]
komisch, denn der stündliche cron-job fürs kompilieren läuft genau auf den stud-pool-rechnern (und der macht auch nur `make distclean && make` in den ganzen verzeichnissen).
wenn du einen error-log hast, kann ich es mir gern anschauen.
